AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: go-test-lambda
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /test
            Method: post
